### ISSUE TITLE
Bug Report: I Can't Press Notes

### ISSUE THREAD

**Issue by Klaskycs** [MobilePorting/Kade-Engine-Community-Mobile#1]
Fix The bug I Can't Press Notes

**Comment by Brenninho123** [comment]
Ainda esta em beta não lancou ainda

**Comment by moxie-coder** [comment]
> Fix The bug I Can't Press Notes

it's in beta right now, so there might be bugs like that

**Comment by Brenninho123** [comment]
> > Corrija o bug que não consigo pressionar notas
> 
> está em beta agora, então pode haver bugs como esse

E foi mal por te irritar em outro dia

**Comment by moxie-coder** [comment]
> > > Corrija o bug que não consigo pressionar notas
> > 
> > 
> > está em beta agora, então pode haver bugs como esse
> 
> E foi mal por te irritar em outro dia

okay

**Comment by moxie-coder** [comment]
I wouldn't say your annoying to me, you're annoying to everyone else

**Comment by Brenninho123** [comment]
> Eu não diria que você é chato para mim, você é chato para todos os outros, inclusive para Nebulosa, porque ele não mantém mais aquele motor

E porque eu não sabia direito quem era os criadores da Andromeda engine me desculpa mesmo

**Comment by moxie-coder** [comment]
> > Eu não diria que você é chato para mim, você é chato para todos os outros, inclusive para Nebulosa, porque ele não mantém mais aquele motor
> 
> E porque eu não sabia direito quem era os criadores da Andromeda engine me desculpa mesmo

really dude, it says it next to the repo name for christ sake, it's plastered everywhere

**Comment by moxie-coder** [comment]
there's seriously no way you actually missed that

**Comment by Brenninho123** [comment]
> não há como você realmente ter perdido isso

Eu vi o seu perfil você ajudou em muitos projetos bons

**Comment by moxie-coder** [comment]
> > não há como você realmente ter perdido isso
> 
> Eu vi o seu perfil você ajudou em muitos projetos bons

yeah I have a lot of connections
